import type { Server } from "@/shared/types/server";

// Static servers registry. Adjust as needed.
export const STATIC_SERVERS: Server[] = [
  {
    id: "vinewood",
    name: "Vinewood",
    icon: "/icons/vinewood.png",
    serverId: 3,
    emoji: "🏰",
  },
  {
    id: "vespucci",
    name: "Vespucci",
    icon: "/icons/vespucci.png",
    serverId: 21,
    emoji: "🛶",
  },
  {
    id: "sunrise",
    name: "Sunrise",
    icon: "/icons/sunrise.png",
    serverId: 6,
    emoji: "🌅",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    icon: "/icons/strawberry.png",
    serverId: 2,
    emoji: "🍓",
  },
  {
    id: "rockford",
    name: "Rockford",
    icon: "/icons/rockford.png",
    serverId: 12,
    emoji: "💎",
  },
  {
    id: "richman",
    name: "Richman",
    icon: "/icons/richman.png",
    serverId: 8,
    emoji: "🤵",
  },
  {
    id: "redwood",
    name: "Redwood",
    icon: "/icons/redwood.png",
    serverId: 17,
    emoji: "🌲",
  },
  {
    id: "rainbow",
    name: "Rainbow",
    icon: "/icons/rainbow.png",
    serverId: 7,
    emoji: "🌈",
  },
  {
    id: "murrieta",
    name: "Murrieta",
    icon: "/icons/murrieta.png",
    serverId: 20,
    emoji: "🌹",
  },
  {
    id: "milton",
    name: "Milton",
    icon: "/icons/milton.png",
    serverId: 22,
    emoji: "🍸",
  },
  {
    id: "la-mesa",
    name: "La Mesa",
    icon: "/icons/la-mesa.png",
    serverId: 10,
    emoji: "🌵",
  },
  {
    id: "insquad",
    name: "Insquad",
    icon: "/icons/insquad.png",
    serverId: 5,
    emoji: "🎭",
  },
  {
    id: "hawick",
    name: "Hawick",
    icon: "/icons/hawick.png",
    serverId: 18,
    emoji: "💵",
  },
  {
    id: "harmony",
    name: "Harmony",
    icon: "/icons/harmony.png",
    serverId: 16,
    emoji: "🌸",
  },
  {
    id: "grapeseed",
    name: "Grapeseed",
    icon: "/icons/grapeseed.png",
    serverId: 19,
    emoji: "🌱",
  },
  {
    id: "eclipse",
    name: "Eclipse",
    icon: "/icons/eclipse.png",
    serverId: 9,
    emoji: "🌘",
  },
  {
    id: "downtown",
    name: "Downtown",
    icon: "/icons/downtown.png",
    serverId: 1,
    emoji: "🌆",
  },
  {
    id: "del-perro",
    name: "Del Perro",
    icon: "/icons/del-perro.png",
    serverId: 14,
    emoji: "🎡",
  },
  {
    id: "davis",
    name: "Davis",
    icon: "/icons/davis.png",
    serverId: 15,
    emoji: "🏀",
  },
  {
    id: "burton",
    name: "Burton",
    icon: "/icons/burton.png",
    serverId: 11,
    emoji: "🏛",
  },
  {
    id: "blackberry",
    name: "Blackberry",
    icon: "/icons/blackberry.png",
    serverId: 4,
    emoji: "🍇",
  },
  {
    id: "alta",
    name: "Alta",
    icon: "/icons/alta.png",
    serverId: 13,
    emoji: "🍀",
  },
];
